stages:
  - deploy
  - run

deploy:
    stage: deploy
    image: registry.i9xp.com.br:8082/docker/forticlient
    when: manual
    allow_failure: false
    environment:
        name: hom
        url: http://frontend.super-e2e.net.br
    only:
      - /^release\/.*$/
      - /^feature\/.*$/
    script:
      - rsync --rsh="sshpass -p ${PASS_DEVELOPMENT_SERVER} ssh -o StrictHostKeyChecking=no -l ${USER_DEVELOPMENT_SERVER}" -azP --exclude '.git' --exclude '.gitlab-ci.yml' ./ ${IP_DEVELOPMENT_SERVER}:/home/${POC_ID}/${HOM_FOLDER}
run:
    stage: run
    image: registry.i9xp.com.br:8082/docker/forticlient
    when: manual
    allow_failure: false
    only:
      - /^release\/.*$/
      - /^feature\/.*$/
    script:
      - export SSHPASS=${PASS_DEVELOPMENT_SERVER}
      - echo "API=${CI_HOM_API}
            BUCKET=${CI_HOM_BUCKET_FILE}" > .front.env
      - rsync --rsh="sshpass -p ${PASS_DEVELOPMENT_SERVER} ssh -o StrictHostKeyChecking=no -l ${USER_DEVELOPMENT_SERVER}" -azP ./.front.env ${IP_DEVELOPMENT_SERVER}:/home/${POC_ID}/docker-builder
      - sshpass -e ssh -p ${SSH_PORT} -o stricthostkeychecking=no ${USER_DEVELOPMENT_SERVER}@${IP_DEVELOPMENT_SERVER} docker-compose -f /home/${POC_ID}/docker-builder/docker-compose.yml up -d --build --force-recreate ${PROJECT_NAME}
